accounts/urls.py
from django.urls.conf import include
from accounts.views import *
from django.urls import path
from django.contrib.auth.views import LogoutView
from django import conf

app_name = 'accounts'
urlpatterns = [
    path('signup/<str:next>/', sign_up, name='signup'),
    path('login/<str:next>/', log_in, name='login'),
    path('profile/', profile, name='profile'),
    path('avatars/', avatars, name='avatars'),
    path('settings/', settings, name='settings'),
    path('logout/', LogoutView.as_view(next_page=conf.settings.LOGOUT_REDIRECT_URL), name='logout'),
    path('user/<str:id>/', view_profile, name='view_user'),
    path('api/', include('accounts.api_urls', namespace='api')),
]

app/urls.py
from os import name
from django.urls import path
from django.views.generic.base import TemplateView
from .views import *
from game.views import check_room
app_name = 'app'
urlpatterns = [
    path('', header, name='header'),
    path('home/', home, name='home'),
    path('single/', single, name='single'),
    path('two/', two, name='two'),
    path('bot/', bot, name='bot'),
    path('ai/', ai, name='ai'),
    path('leaderboard/', board, name='board'),
    path('local/', local, name='local'),
    path('online/', online, name='online'),
    path('notifications/', notifications, name='notifications'),
    path('game/', game, name='game'),
    path('game/check_room/', check_room, name='check_room'),
    path('about/', about, name='about'),
    path('new_game/', new_game, name='new_game'),
    path('manifest.js', TemplateView.as_view(template_name='app/manifest.webmanifest', content_type='application/x-javascript'), name='manifest'),
    path('sw.js', TemplateView.as_view(template_name='app/sw.js', content_type='application/x-javascript'), name='worker'),
]

chat/urls.py
from django.urls import path
from .views import *
app_name = 'chat'

urlpatterns = [
    path('', chat, name='chat'),
    path('older/', older_messages, name='older_messages')
]

root/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls', namespace='main')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('chat/', include('chat.urls', namespace='chat')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import ugettext_lazy as _
from django.urls import reverse
from django.core.files.base import ContentFile
from .managers import Manager

import uuid
from PIL import Image
from io import BytesIO
from PIL.ImageOps import exif_transpose

# Create your models here.

class CustomUser(AbstractUser):
    username = None
    email = models.EmailField(_('email address'), unique=True)
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    front_id = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
    won_games = models.IntegerField(default=0)
    lost_games = models.IntegerField(default=0)
    draw_games = models.IntegerField(default=0)
    image = models.ImageField(default='images/default.png', upload_to='images')
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []
    objects = Manager()

    @property
    def total_games(self):
        return self.won_games + self.lost_games + self.draw_games

    @property
    def name(self):
        return self.__str__()

    @property
    def profile_url(self):
        return reverse('accounts:view_user', kwargs={"id":self.front_id})


    def compress(self, im:Image):
        ratio = im.height / im.width
        height = 100
        width = round(height / ratio)
        # create a BytesIO object
        im_io = BytesIO() 
        # save image to BytesIO object
        im = exif_transpose(im)

        im = im.resize([height,width], Image.ANTIALIAS)
        
        im = im.convert("RGB")
        im = im.save(im_io,'JPEG', quality=70) 
        # create a django-friendly Files object
        im = ContentFile(im_io.getvalue(), name=self.name+"ProfilePic.jpeg")
        return  im

    def save(self, *args, **kwargs):

        image = Image.open(self.image)
        if image.height > 100:
            image = self.compress(image)
            self.image = image
        super(AbstractUser, self).save(*args, **kwargs)


    def __str__(self):
        return f"{self.first_name} {self.last_name}"
    

class Notification(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='notification')
    invitor = models.ForeignKey(CustomUser, null=True, blank=True, on_delete=models.CASCADE, related_name='invitation')
    room = models.CharField(max_length=16)
    time = models.DateTimeField(auto_now_add=True)

    @property
    def content(self):
        if self.invitor:
            return f'Your friend {self.invitor.name} challenged you to play together click to play now !\nThis invitation is valid for 1 minute'
        else:
            return f'A friend challenged you to play together click to play now !\nThis invitation is valid for 1 minute'
    
    @property
    def arabic(self):
        if self.invitor:
            return f'صديقك {self.invitor.name} يتحداك لتلعب معه اضغط الآن لقبول التحدي...هذه الدعوة صالحة لمدة دقيقة واحدة'
        return 'صديق لك يتحداك للعب مباراة ... اضغط هنا لقبول التحدي'

    @property
    def url(self):
        return reverse('app:game') + f'?room={self.room}'

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = CustomUser
        fields = ('first_name', 'last_name','email', 'password1', 'password2')


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ('first_name', 'last_name', 'email', 'image')

accounts/views.py
from django.db.models.query_utils import Q
from django.shortcuts import redirect, render
from django.contrib import messages
from django.contrib.auth import login, authenticate
from django.shortcuts import get_object_or_404
from .forms import CustomUserCreationForm, CustomUserChangeForm
from .models import CustomUser
from accounts.decorators import *
from game.models import Match

# Create your views here.
@restrict_logged
def sign_up(request, next):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            email = form.cleaned_data.get('email')
            password = form.cleaned_data.get('password1')
            user = authenticate(request, email=email, password=password)
            if user:
                login(request, user)
                pathes = {
                    'profile':'accounts:profile',
                    'chat':'chat:chat',
                    'settings':'accounts:settings',
                    'game':'app:game',
                    'online':'app:online',
                    'notifications':'app:notifications',
                    'new_game':'app:new_game',
                    'avatars':'accounts:avatars'
                }
                return redirect(pathes.get(next, 'app:header'))
    else:
        form = CustomUserCreationForm()
    context = {
        'form':form,
        'next':next,
    }
    return render(request, 'accounts/signup.html', context)

@restrict_logged
def log_in(request, next):
    if request.method == 'POST':
        user = authenticate(request, email=request.POST.get('email'), password=request.POST.get('password'))
        if user:
            login(request, user)
            pathes = {
                    'profile':'accounts:profile',
                    'chat':'chat:chat',
                    'settings':'accounts:settings',
                    'game':'app:game',
                    'online':'app:online',
                    'notifications':'app:notifications',
                    'new_game':'app:new_game',
                    'avatars':'accounts:avatars'
                }
            return redirect(pathes.get(next, 'app:header'))
        else:
            messages.error(request, 'Wrong user name or password please check your info')
    
    return render(request, 'accounts/login.html', {'next':next})

@restrict_unlogged(next='profile')
def profile(request):
    try:
        rate = round((request.user.won_games/ request.user.total_games) *100, 1) 
    except ZeroDivisionError:
        rate = 0

    history = Match.objects.filter(Q(winner=request.user)|Q(loser=request.user)) | request.user.matches.all()
    history = history.order_by('-time')[:20]
    context =  {
        'win_rate': rate,
        'history': history
    }
    return render(request, 'accounts/profile.html', context)

@restrict_unlogged(next='settings')
def settings(request):
    if request.method == "POST":
        form = CustomUserChangeForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('accounts:profile')
    return render(request, 'accounts/settings.html')

@restrict_unlogged(next='avatars')
def avatars(request):
    if request.method == 'POST':
        choice = int(request.POST.get('choice'))
        if choice in range(1, 5):
            user = request.user
            user.image = f'images/{choice}.png'
            user.save()
            return redirect('accounts:profile')
        else:
            return redirect('accounts:profile')
    return render(request, 'accounts/avatars.html')



def view_profile(request, id):
    user = get_object_or_404(CustomUser, front_id=id)
    if user == request.user:
        return redirect('accounts:profile')
    if user.total_games == 0:
        rate = 0
    else:
        rate = round((user.won_games/ user.total_games)* 100, 1)  
    return render(request, 'accounts/view_profile.html', {'friend':user, 'win_rate':rate})

accounts/templates/accounts/avatars.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home | XO Online</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=BioRhyme:wght@400&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://ahmed0saber.github.io/XO-online/external-files/style.css">

    <link rel="manifest" href="{% url 'app:manifest' %}">
    <link rel="icon" href="{% static 'logo/tic-tac-toe.svg' %}">
    <meta name="theme-color" content="#1282A2">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script>
        $(document).ready(function () {

            $("img").click(function () {
                $("img").css("background-color", "#EEE");
                $(this).css("background-color", "#1282A2");
            });

            $("#pic1").click(function () {
                $("#pic_id").val("1");
            });
            $("#pic2").click(function () {
                $("#pic_id").val("2");
            });
            $("#pic3").click(function () {
                $("#pic_id").val("3");
            });
            $("#pic4").click(function () {
                $("#pic_id").val("4");
            });
        });
    </script>

    <style>
        img{
            height: 100px;
            width: 100px;
            padding: 5px;
            border-radius: 50%;
        }
        #space{
            height: 120px;
            width: 120px;
            padding: 5px;
            margin: auto;
            border-radius: 50%;
            opacity: 0.6;
            transition-duration: 0.8s;
        }
        #space:hover{
            opacity: 1;
        }
        #pics{
            display: flex;
            flex-wrap: wrap;
        }
        #title{
            padding: 5px;
        }
        input{
            padding: 8px 36px;
            color: #f7f7f7;
            background-color: #1282A2;
            font-size: 18px;
            border: none;
            border-radius: 3px;
            display: block;
            margin: 0 auto;
        }
        p{
            font-size: 22px;
            text-align: center;
            color: #f7f7f7;
        }
    </style>
</head>
<body>
    <div class="loader">
        <div class="circle"></div>
    </div>
    <header>
        <span class="logo">XO Online</span>
        <nav>
            <div>
                <a class="active" href="{% url 'app:header' %}"><i class="fa fa-home"></i> <span>Home</span></a>
                <a href="{% url 'app:board' %}"><i class="fa fa-trophy"></i> <span>Leaderboard</span></a>
                <a href="{% url 'chat:chat' %}"><i class="fa fa-envelope"></i> <span>Chat</span></a>
                <a href="{% url 'app:notifications' %}"><i class="fa fa-bell"></i> <span>Notifications</span></a>
                <a href="{% url 'accounts:profile' %}"><i class="fa fa-user"></i> <span>Profile</span></a>
            </div>
        </nav>
    </header>
    <main>
        <section class="home">
            <div id="title">
                <p id="p1">‹Choose a picture›</p>
            </div>
            <div id="pics">
                <div id="space">
                    <img id="pic1" src="https://xoonlinebucket.s3.amazonaws.com/images/1.png">
                </div>
                <div id="space">
                    <img id="pic2" src="https://xoonlinebucket.s3.amazonaws.com/images/2.png">
                </div>
                <div id="space">
                    <img id="pic3" src="https://xoonlinebucket.s3.amazonaws.com/images/3.png">
                </div>
                <div id="space">
                    <img id="pic4" src="https://xoonlinebucket.s3.amazonaws.com/images/4.png">
                </div>
            </div>
            <div id="hidden_form">
                <form method="POST" action="" enctype="multipart/form-data">
                    {% csrf_token %}
                    <input type="hidden" value="0" id="pic_id" name="choice" action="">
                    <input type="submit" id="btn" value="Save">
                </form>
            </div>
        </section>
    </main>
</body>
<script src="https://ahmed0saber.github.io/XO-online/external-files/script.js"></script>
<script src="https://kit.fontawesome.com/282bcf757e.js" crossorigin="anonymous"></script>
</html>

accounts/templates/accounts/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login | XO Online</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=BioRhyme:wght@400&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://ahmed0saber.github.io/XO-online/external-files/style.css">
</head>
<body>
    <div class="loader">
        <div class="circle"></div>
    </div>
    <header>
        <span class="logo">XO Online</span>
        <nav>
            <div>
                <a class="active" href="{% url 'app:header' %}"><i class="fa fa-home"></i> <span>Home</span></a>
                <a href="{% url 'app:board' %}"><i class="fa fa-trophy"></i> <span>Leaderboard</span></a>
                <a href="{% url 'chat:chat' %}"><i class="fa fa-envelope"></i> <span>Chat</span></a>
                <a href="{% url 'app:notifications' %}"><i class="fa fa-bell"></i> <span>Notifications</span></a>
                <a href="{% url 'accounts:profile' %}"><i class="fa fa-user"></i> <span>Profile</span></a>
            </div>
        </nav>
    </header>
    <main>
        <section class="form">
            <h2>Login to continue</h2>
            <form action="" method="POST">
                {% csrf_token %}
                <input type="email" name="email" placeholder="Email">
                <input type="password" name="password" placeholder="Password">
                <button>Log in</button>
                {% if messages %}
                {% for message in messages %}
                <p>{{ message }}</p>
                {% endfor %}
                {% endif %}
                <p>Don't have account ? <a href="{% url 'accounts:signup' next%}">Create one</a></p>
            </form>
        </section>
    </main>
</body>
<script src="https://ahmed0saber.github.io/XO-online/external-files/script.js"></script>
<script src="https://kit.fontawesome.com/282bcf757e.js" crossorigin="anonymous"></script>
</html>

accounts/templates/accounts/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Profile | XO Online</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=BioRhyme:wght@400&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://ahmed0saber.github.io/XO-online/external-files/style.css">
</head>
<body>
    <div class="loader">
        <div class="circle"></div>
    </div>
    <header>
        <span class="logo">XO Online</span>
        <nav>
            <div>
                <a href="{% url 'app:header' %}"><i class="fa fa-home"></i> <span>Home</span></a>
                <a href="{% url 'app:board' %}"><i class="fa fa-trophy"></i> <span>Leaderboard</span></a>
                <a href="{% url 'chat:chat' %}"><i class="fa fa-envelope"></i> <span>Chat</span></a>
                <a href="{% url 'app:notifications' %}"><i class="fa fa-bell"></i> <span>Notifications</span></a>
                <a class="active" href="{% url 'accounts:profile' %}"><i class="fa fa-user"></i> <span>Profile</span></a>
            </div>
        </nav>
    </header>
    <main>
        <section class="home">
            <section class="logo-container">
                <img src="{{ user.image.url }}">
            </section>
            <section class="profile-controls">
                <h3>{{ user }}</h3>
                <div class="col-btns">
                    <a onclick="logout()">Log out</a>
                    <a href="{% url 'accounts:settings' %}">Edit Profile</a>
                    <a onclick="copylink()">Share</a>
                </div>
                <p>Played {{ user.total_games }} games</p>
                <p>Win: {{ user.won_games }}</p>
                <p>Lose: {{ user.lost_games }}</p>
                <p>Draw: {{ user.draw_games }}</p>
                <p>Win rate: {{ win_rate }} %</p>
            </section>
        </section>
        <section class="match-history">
            <h2>Recent {{ history.count }} Games</h2>
            {% for match in history %}
            {% if match.winner == user %}
            <fieldset>
                <legend class="win">win</legend>
                <p>You VS {{ match.loser }}</p>
                <span>{{match.time|date:'M. j, g:i A'}}</span>
            </fieldset>
            {% elif match.loser == user %}
            <fieldset>
                <legend class="lose">lose</legend>
                <p>You VS {{ match.winner }}</p>
                <span>{{match.time|date:'M. j, g:i A'}}</span>
            </fieldset>
            {% else %}
            <fieldset>
                <legend class="draw">draw</legend>
                <p>You VS
                    {% for player in match.draw.all %}
                    {% if player != user %}
                    {{player}}
                    {%  endif %}
                    {% endfor %}
                </p>
                <span>{{match.time|date:'M. j, g:i A'}}</span>
            </fieldset>
            {% endif %}
            {% endfor %}
        </section>
    </main>
</body>
<script>
var user_id = "{{user.front_id}}";
function copylink(){
    var TempText = document.createElement("input");
    var url = window.location.href
    var TextToCopy = url.slice(0, url.indexOf("/", 10)+1) + "accounts/user/"+user_id;
    TempText.value = TextToCopy;
    document.body.appendChild(TempText);
    TempText.select();
    document.execCommand("copy");
    document.body.removeChild(TempText);
    alert("Copied the text : " + TempText.value);
}
function logout(){
    let isExecuted = confirm("Are you sure to log out ?!");
    if(isExecuted){
        window.open("{% url 'accounts:logout' %}" , "_self");
    }
}
</script>
<script src="https://ahmed0saber.github.io/XO-online/external-files/script.js"></script>
<script src="https://kit.fontawesome.com/282bcf757e.js" crossorigin="anonymous"></script>
</html>

accounts/templates/accounts/settings.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit | XO Online</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=BioRhyme:wght@400&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://ahmed0saber.github.io/XO-online/external-files/style.css">
    <script>
        window.addEventListener('load', function() {
            document.querySelector('input[type="file"]').addEventListener('change', function() {
                if (this.files && this.files[0]) {
                    var img = document.querySelector('img');
                    img.onload = () => {
                        URL.revokeObjectURL(img.src);  // no longer needed, free memory
                    }
                    img.src = URL.createObjectURL(this.files[0]); // set src to blob url
                }
            });
        });
        function goavatars()
        {
            window.open("{% url 'accounts:avatars' %}","_self");
        }
    </script>
</head>
<body>
    <div class="loader">
        <div class="circle"></div>
    </div>
    <header>
        <span class="logo">XO Online</span>
        <nav>
            <div>
                <a href="{% url 'app:header' %}"><i class="fa fa-home"></i> <span>Home</span></a>
                <a href="{% url 'app:board' %}"><i class="fa fa-trophy"></i> <span>Leaderboard</span></a>
                <a href="{% url 'chat:chat' %}"><i class="fa fa-envelope"></i> <span>Chat</span></a>
                <a href="{% url 'app:notifications' %}"><i class="fa fa-bell"></i> <span>Notifications</span></a>
                <a class="active" href="{% url 'accounts:profile' %}"><i class="fa fa-user"></i> <span>Profile</span></a>
            </div>
        </nav>
    </header>
    <main>
        <section class="home">
            <section class="logo-container">
                <img src="{{ user.image.url }}">
            </section>
            <section class="profile-controls">
                <section class="profile-controls">
                    <form method="POST" action="" enctype="multipart/form-data">
                        {% csrf_token %}
                        <p>First Name</p>
                        <input type="text" placeholder="First Name" value="{{ user.first_name }}" name="first_name">
                        <p>Last Name</p>
                        <input type="text" placeholder="Last Name" value="{{ user.last_name }}" name="last_name">
                        <p>Email Address</p>
                        <input type="email" placeholder="Email" value="{{ user.email }}" name="email">
                        <p>Change Profile Picture</p>
                        <input type="file" id="selectedFile" style="display: none;"  name="image"/>
                        <div class="col-btns">
                            <a onclick="document.getElementById('selectedFile').click();">From Device</a>
                            <a href="{% url 'accounts:avatars' %}">From Avatars</a>
                        </div>
                        <button type="submit">Save</button>
                    </form>
                </section>
            </section>
        </section>
    </main>
</body>
<script src="https://ahmed0saber.github.io/XO-online/external-files/script.js"></script>
<script src="https://kit.fontawesome.com/282bcf757e.js" crossorigin="anonymous"></script>
</html>

accounts/templates/accounts/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Signup | XO Online</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=BioRhyme:wght@400&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://ahmed0saber.github.io/XO-online/external-files/style.css">
</head>
<body>
    <div class="loader">
        <div class="circle"></div>
    </div>
    <header>
        <span class="logo">XO Online</span>
        <nav>
            <div>
                <a class="active" href="{% url 'app:header' %}"><i class="fa fa-home"></i> <span>Home</span></a>
                <a href="{% url 'app:board' %}"><i class="fa fa-trophy"></i> <span>Leaderboard</span></a>
                <a href="{% url 'chat:chat' %}"><i class="fa fa-envelope"></i> <span>Chat</span></a>
                <a href="{% url 'app:notifications' %}"><i class="fa fa-bell"></i> <span>Notifications</span></a>
                <a href="{% url 'accounts:profile' %}"><i class="fa fa-user"></i> <span>Profile</span></a>
            </div>
        </nav>
    </header>
    <main>
        <section class="form">
            <h2>Create new account</h2>
            <form action="" method="POST">
                {% csrf_token %}
                <input type="text" placeholder="First Name" name="first_name">
                <input type="text" placeholder="Last Name" name="last_name">
                <input type="email" placeholder="Email" name="email">
                <div class='errors' id='email_errors'></div>
                {{form.email.errors}}
                <input type="password" placeholder="Password" name="password1">
                <div class='errors' id='pass_errors'></div>
                {{form.password1.errors}}
                <input type="password" placeholder="Confirm Password" name="password2">
                <div class='errors' id='pass2_errors'></div>
                {{form.password2.errors}}
                <button type="submit">Sign up</button>
                <p>Already have account ? <a href="{% url 'accounts:login' next%}">Log in</a></p>
            </form>
        </section>
    </main>
</body>
<script>
let email = document.getElementById('email')
email.oninput = async ()=>{
    if (email.value == ''){
        email.classList = ''
        document.getElementById('email_errors').innerHTML = ''
        return
    }
    let res = await fetch(`/accounts/api/check_email/?email=${email.value}`)
    if (res.ok){
        email.classList = 'right'
        document.getElementById('email_errors').innerHTML = ''
    }else{
        console.clear()
        email.classList = 'wrong'
        res = await res.json()
        document.getElementById('email_errors').innerHTML ='' 
        for (err of res.details){
        document.getElementById('email_errors').innerHTML += `<p class='errors'>${err}</p>` 
        }
    }
}

let password = document.getElementById('password1')
password.oninput = async ()=>{
    if (password.value == ''){
        password.classList = ''
        document.getElementById('pass_errors').innerHTML = ''
        return
    }
    let res = await fetch(`/accounts/api/check_password/?password=${password.value}`)
    if (res.ok){
        password.classList = 'right'
        document.getElementById('pass_errors').innerHTML = ''
    }else{
        console.clear()
        password.classList = 'wrong'
        res = await res.json()
        document.getElementById('pass_errors').innerHTML = '' 
        for (err of res.details){
            document.getElementById('pass_errors').innerHTML += `<p class='errors'>${err}</p>` 
        }
    }
}

let password2 = document.getElementById('password2')
password2.oninput = ()=>{
    if (password2.value == password.value){
        password2.classList = 'right'
        document.getElementById('pass2_errors').innerHTML = ''
    }else{
        password2.classList = 'wrong'
        document.getElementById('pass2_errors').innerHTML = 'Two passwords must be the same' 
    }
}
</script>
<script src="https://ahmed0saber.github.io/XO-online/external-files/script.js"></script>
<script src="https://kit.fontawesome.com/282bcf757e.js" crossorigin="anonymous"></script>
</html>

accounts/templates/accounts/view_profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Share | XO Online</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=BioRhyme:wght@400&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://ahmed0saber.github.io/XO-online/external-files/style.css">
</head>
<body>
    <div class="loader">
        <div class="circle"></div>
    </div>
    <header>
        <span class="logo">XO Online</span>
        <nav>
            <div>
                <a class="active" href="{% url 'app:header' %}"><i class="fa fa-home"></i> <span>Home</span></a>
                <a href="{% url 'app:board' %}"><i class="fa fa-trophy"></i> <span>Leaderboard</span></a>
                <a href="{% url 'chat:chat' %}"><i class="fa fa-envelope"></i> <span>Chat</span></a>
                <a href="{% url 'app:notifications' %}"><i class="fa fa-bell"></i> <span>Notifications</span></a>
                <a href="{% url 'accounts:profile' %}"><i class="fa fa-user"></i> <span>Profile</span></a>
            </div>
        </nav>
    </header>
    <main>
        <section class="home">
            <section class="logo-container">
                <img src="{{ friend.image.url }}">
            </section>
            <section class="profile-controls">
                <h3>{{ friend }}</h3>
                <div class="col-btns">
                    <a href="{% url 'app:game' %}?room=invite&user={{friend.front_id}}">Play Together</a>
                </div>
                <p>Played {{ friend.total_games }} games</p>
                <p>Win: {{ friend.won_games }}</p>
                <p>Lose: {{ friend.lost_games }}</p>
                <p>Draw: {{ friend.draw_games }}</p>
                <p>Win rate: {{ win_rate }} %</p>
            </section>
        </section>
    </main>
</body>
<script src="https://ahmed0saber.github.io/XO-online/external-files/script.js"></script>
<script src="https://kit.fontawesome.com/282bcf757e.js" crossorigin="anonymous"></script>
</html>