accounts/urls.py
from django.urls.conf import include
from accounts.views import *
from django.urls import path
from django.contrib.auth.views import LogoutView
from django import conf

app_name = 'accounts'
urlpatterns = [
    path('signup/<str:next>/', sign_up, name='signup'),
    path('login/<str:next>/', log_in, name='login'),
    path('profile/', profile, name='profile'),
    path('avatars/', avatars, name='avatars'),
    path('settings/', settings, name='settings'),
    path('logout/', LogoutView.as_view(next_page=conf.settings.LOGOUT_REDIRECT_URL), name='logout'),
    path('user/<str:id>/', view_profile, name='view_user'),
    path('api/', include('accounts.api_urls', namespace='api')),
]

app/urls.py
from os import name
from django.urls import path
from django.views.generic.base import TemplateView
from .views import *
from game.views import check_room
app_name = 'app'
urlpatterns = [
    path('', header, name='header'),
    path('home/', home, name='home'),
    path('single/', single, name='single'),
    path('two/', two, name='two'),
    path('bot/', bot, name='bot'),
    path('ai/', ai, name='ai'),
    path('leaderboard/', board, name='board'),
    path('local/', local, name='local'),
    path('online/', online, name='online'),
    path('notifications/', notifications, name='notifications'),
    path('game/', game, name='game'),
    path('game/check_room/', check_room, name='check_room'),
    path('about/', about, name='about'),
    path('new_game/', new_game, name='new_game'),
    path('manifest.js', TemplateView.as_view(template_name='app/manifest.webmanifest', content_type='application/x-javascript'), name='manifest'),
    path('sw.js', TemplateView.as_view(template_name='app/sw.js', content_type='application/x-javascript'), name='worker'),
]

chat/urls.py
from django.urls import path
from .views import *
app_name = 'chat'

urlpatterns = [
    path('', chat, name='chat'),
    path('older/', older_messages, name='older_messages')
]

root/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls', namespace='main')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('chat/', include('chat.urls', namespace='chat')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))

app/templates/app/ai_bot.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hard | XO Online</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=BioRhyme:wght@400&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://ahmed0saber.github.io/XO-online/external-files/style.css">
</head>
<body>
    <div class="loader">
        <div class="circle"></div>
    </div>
    <header>
        <span class="logo">XO Online</span>
        <nav>
            <div>
                <a class="active" href="{% url 'app:header' %}"><i class="fa fa-home"></i> <span>Home</span></a>
                <a href="{% url 'app:board' %}"><i class="fa fa-trophy"></i> <span>Leaderboard</span></a>
                <a href="{% url 'chat:chat' %}"><i class="fa fa-envelope"></i> <span>Chat</span></a>
                <a href="{% url 'app:notifications' %}"><i class="fa fa-bell"></i> <span>Notifications</span></a>
                <a href="{% url 'accounts:profile' %}"><i class="fa fa-user"></i> <span>Profile</span></a>
            </div>
        </nav>
    </header>
    <main>
        <section class="home">
            <section class="logo-container">
                <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="300" height="300" viewBox="0 0 265 300"><defs><style>.a{clip-path:url(#g);}.b{fill:#1282a2;}.b,.c,.d{font-size:200px;font-family:"BioRhyme";}.c{fill:#f7fff7;}.d{fill:#fff;}.e{fill:#2e3532;}.f{filter:url(#c);}.g{filter:url(#a);}</style><filter id="a" x="13.5" y="-24.5" width="199" height="275" filterUnits="userSpaceOnUse"><feOffset dx="3" dy="3" input="SourceAlpha"/><feGaussianBlur stdDeviation="1.5" result="b"/><feFlood/><feComposite operator="in" in2="b"/><feComposite in="SourceGraphic"/></filter><filter id="c"><feOffset dx="3" dy="3" input="SourceAlpha"/><feGaussianBlur stdDeviation="1.5" result="d"/><feFlood flood-opacity="0.702" result="e"/><feComposite operator="out" in="SourceGraphic" in2="d"/><feComposite operator="in" in="e"/><feComposite operator="in" in2="SourceGraphic"/></filter><clipPath id="g"><rect width="300" height="300"/></clipPath></defs><g id="f" class="a"><rect class="e" width="300" height="300"/><g class="g" transform="matrix(1, 0, 0, 1, 0, 0)"><text class="b" transform="translate(17 187)"><tspan x="0" y="0">X</tspan></text></g><g data-type="innerShadowGroup"><text class="c" transform="translate(113 244)"><tspan x="0" y="0">O</tspan></text><g class="f" transform="matrix(1, 0, 0, 1, 0, 0)"><text class="d" transform="translate(113 244)"><tspan x="0" y="0">O</tspan></text></g></g></g></svg>
            </section>
            <section class="btns" id="pickxo">
                <p>Pick one that you want to play with !</p>
                <p>Notice that X plays the first turn.</p>
                <a onclick="pickit('X')">X</a>
                <a onclick="pickit('O')">O</a>
                <a href="{% url 'app:single' %}"><i class="fa fa-angle-left"></i> Back</a>
            </section>

            <section id="play">
                <p id="picked">000</p>
                <div class="grid-container" onclick="done('0')">
                    <p class="grid"></p>
                </div>
                <div class="grid-container" onclick="done('1')">
                    <p class="grid"></p>
                </div>
                <div class="grid-container" onclick="done('2')">
                    <p class="grid"></p>
                </div>

                <div class="grid-container" onclick="done('3')">
                    <p class="grid"></p>
                </div>
                <div class="grid-container" onclick="done('4')">
                    <p class="grid"></p>
                </div>
                <div class="grid-container" onclick="done('5')">
                    <p class="grid"></p>
                </div>

                <div class="grid-container" onclick="done('6')">
                    <p class="grid"></p>
                </div>
                <div class="grid-container" onclick="done('7')">
                    <p class="grid"></p>
                </div>
                <div class="grid-container" onclick="done('8')">
                    <p class="grid"></p>
                </div>

                <div class="btn-container">
                    <button onclick="restart()" class="btns">Restart</button>
                </div>
            </section>
        </section>
    </main>
</body>
<script src="https://ahmed0saber.github.io/XO-online/external-files/script.js"></script>
<script src="https://ahmed0saber.github.io/XO-online/external-files/hard.js"></script>
<script src="https://kit.fontawesome.com/282bcf757e.js" crossorigin="anonymous"></script>
</html>

app/templates/app/leaderboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Leaderboard | XO Online</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=BioRhyme:wght@400&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://ahmed0saber.github.io/XO-online/external-files/style.css">
</head>
<body>
    <div class="loader">
        <div class="circle"></div>
    </div>
    <header>
        <span class="logo">XO Online</span>
        <nav>
            <div>
                <a href="{% url 'app:header' %}"><i class="fa fa-home"></i> <span>Home</span></a>
                <a class="active" href="{% url 'app:board' %}"><i class="fa fa-trophy"></i> <span>Leaderboard</span></a>
                <a href="{% url 'chat:chat' %}"><i class="fa fa-envelope"></i> <span>Chat</span></a>
                <a href="{% url 'app:notifications' %}"><i class="fa fa-bell"></i> <span>Notifications</span></a>
                <a href="{% url 'accounts:profile' %}"><i class="fa fa-user"></i> <span>Profile</span></a>
            </div>
        </nav>
    </header>
    <main>
        <section class="home leaderboard">
            <section class="others">
                {% for user in users %}
                <a href="{% url 'accounts:view_user' user.front_id %}">
                    <div class="row">
                        <div id="rank">
                            <p>{{ forloop.counter }}</p>
                        </div>
                        <div id="pic">
                            <img src="{{ user.image.url }}">
                        </div>
                        <div id="name">
                            <p>{{ user }}</p>
                        </div>
                        <div id="score">
                            <p>{{ user.won_games }}</p>
                        </div>
                    </div>
                </a>
                {% endfor %}
            </section>
        </section>
    </main>
</body>
<script src="https://ahmed0saber.github.io/XO-online/external-files/script.js"></script>
<script src="https://kit.fontawesome.com/282bcf757e.js" crossorigin="anonymous"></script>
</html>

app/templates/app/new_game.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Online | XO Online</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=BioRhyme:wght@400&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://ahmed0saber.github.io/XO-online/external-files/style.css">
</head>
<body>
    <div class="loader">
        <div class="circle"></div>
    </div>
    <header>
        <span class="logo">XO Online</span>
        <nav>
            <div>
                <a class="active" href="{% url 'app:header' %}"><i class="fa fa-home"></i> <span>Home</span></a>
                <a href="{% url 'app:board' %}"><i class="fa fa-trophy"></i> <span>Leaderboard</span></a>
                <a href="{% url 'chat:chat' %}"><i class="fa fa-envelope"></i> <span>Chat</span></a>
                <a href="{% url 'app:notifications' %}"><i class="fa fa-bell"></i> <span>Notifications</span></a>
                <a href="{% url 'accounts:profile' %}"><i class="fa fa-user"></i> <span>Profile</span></a>
            </div>
        </nav>
    </header>
    <main>
        <section class="home">
            <section class="logo-container">
                <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="300" height="300" viewBox="0 0 265 300"><defs><style>.a{clip-path:url(#g);}.b{fill:#1282a2;}.b,.c,.d{font-size:200px;font-family:"BioRhyme";}.c{fill:#f7fff7;}.d{fill:#fff;}.e{fill:#2e3532;}.f{filter:url(#c);}.g{filter:url(#a);}</style><filter id="a" x="13.5" y="-24.5" width="199" height="275" filterUnits="userSpaceOnUse"><feOffset dx="3" dy="3" input="SourceAlpha"/><feGaussianBlur stdDeviation="1.5" result="b"/><feFlood/><feComposite operator="in" in2="b"/><feComposite in="SourceGraphic"/></filter><filter id="c"><feOffset dx="3" dy="3" input="SourceAlpha"/><feGaussianBlur stdDeviation="1.5" result="d"/><feFlood flood-opacity="0.702" result="e"/><feComposite operator="out" in="SourceGraphic" in2="d"/><feComposite operator="in" in="e"/><feComposite operator="in" in2="SourceGraphic"/></filter><clipPath id="g"><rect width="300" height="300"/></clipPath></defs><g id="f" class="a"><rect class="e" width="300" height="300"/><g class="g" transform="matrix(1, 0, 0, 1, 0, 0)"><text class="b" transform="translate(17 187)"><tspan x="0" y="0">X</tspan></text></g><g data-type="innerShadowGroup"><text class="c" transform="translate(113 244)"><tspan x="0" y="0">O</tspan></text><g class="f" transform="matrix(1, 0, 0, 1, 0, 0)"><text class="d" transform="translate(113 244)"><tspan x="0" y="0">O</tspan></text></g></g></g></svg>
            </section>
            <section class="btns">
                <p>Play an auto matching game.</p>
                <a href="{% url 'app:game' %}?room=random">Search for a game</a>
                <hr>
                <p>Play a custom game.</p>
                <a href="{% url 'app:game' %}?room=create">Create room</a>
                <p>or</p>
                <input type="text" placeholder="Room Code">
                <p id='response'></p>
                <a id='join' href="">Join room</a>
                <a href="{% url 'app:two' %}"><i class="fa fa-angle-left"></i> Back</a>
            </section>
        </section>
    </main>
</body>
<script>
let check_room = async room => {
    let url = "{%url 'app:check_room' %}?room=" + room
    let res = await fetch(url)
    if (res.ok) {
        res = await res.json()
        document.querySelector('input').style.borderColor = 'green'
        document.querySelector('input').style.outlineColor = 'green'
        document.getElementById('response').innerText = res.message
        return true
    } else {
        res = await res.json()
        document.querySelector('input').style.borderColor = 'red'
        document.querySelector('input').style.outlineColor = 'red'
        document.getElementById('response').innerText = res.error
        return false
    }
}
document.querySelector('input').onkeypress =  (e) => {
    if (e.keyCode == 13) {
        document.getElementById('join').click()
    }
}
document.querySelector('input').oninput =  async (e) => {
    let is_valid = await check_room(e.target.value)
    if (is_valid){
        document.getElementById('join').href = `{% url 'app:game' %}?room=${e.target.value}`
    }else{
        document.getElementById('join').href = '#'
    }
}
</script>
<script src="https://ahmed0saber.github.io/XO-online/external-files/script.js"></script>
<script src="https://kit.fontawesome.com/282bcf757e.js" crossorigin="anonymous"></script>
</html>

app/templates/app/single.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Single Player | XO Online</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=BioRhyme:wght@400&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://ahmed0saber.github.io/XO-online/external-files/style.css">
</head>
<body>
    <div class="loader">
        <div class="circle"></div>
    </div>
    <header>
        <span class="logo">XO Online</span>
        <nav>
            <div>
                <a class="active" href="{% url 'app:header' %}"><i class="fa fa-home"></i> <span>Home</span></a>
                <a href="{% url 'app:board' %}"><i class="fa fa-trophy"></i> <span>Leaderboard</span></a>
                <a href="{% url 'chat:chat' %}"><i class="fa fa-envelope"></i> <span>Chat</span></a>
                <a href="{% url 'app:notifications' %}"><i class="fa fa-bell"></i> <span>Notifications</span></a>
                <a href="{% url 'accounts:profile' %}"><i class="fa fa-user"></i> <span>Profile</span></a>
            </div>
        </nav>
    </header>
    <main>
        <section class="home">
            <section class="logo-container">
                <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="300" height="300" viewBox="0 0 265 300"><defs><style>.a{clip-path:url(#g);}.b{fill:#1282a2;}.b,.c,.d{font-size:200px;font-family:"BioRhyme";}.c{fill:#f7fff7;}.d{fill:#fff;}.e{fill:#2e3532;}.f{filter:url(#c);}.g{filter:url(#a);}</style><filter id="a" x="13.5" y="-24.5" width="199" height="275" filterUnits="userSpaceOnUse"><feOffset dx="3" dy="3" input="SourceAlpha"/><feGaussianBlur stdDeviation="1.5" result="b"/><feFlood/><feComposite operator="in" in2="b"/><feComposite in="SourceGraphic"/></filter><filter id="c"><feOffset dx="3" dy="3" input="SourceAlpha"/><feGaussianBlur stdDeviation="1.5" result="d"/><feFlood flood-opacity="0.702" result="e"/><feComposite operator="out" in="SourceGraphic" in2="d"/><feComposite operator="in" in="e"/><feComposite operator="in" in2="SourceGraphic"/></filter><clipPath id="g"><rect width="300" height="300"/></clipPath></defs><g id="f" class="a"><rect class="e" width="300" height="300"/><g class="g" transform="matrix(1, 0, 0, 1, 0, 0)"><text class="b" transform="translate(17 187)"><tspan x="0" y="0">X</tspan></text></g><g data-type="innerShadowGroup"><text class="c" transform="translate(113 244)"><tspan x="0" y="0">O</tspan></text><g class="f" transform="matrix(1, 0, 0, 1, 0, 0)"><text class="d" transform="translate(113 244)"><tspan x="0" y="0">O</tspan></text></g></g></g></svg>
            </section>
            <section class="btns">
                <p>Which mode do you prefer to play ?</p>
                <p>Notice that hard mode is unbeatable.</p>
                <a href="{% url 'app:bot' %}">Easy</a>
                <a href="{% url 'app:ai' %}">Hard</a>
                <a href="{% url 'app:header' %}"><i class="fa fa-angle-left"></i> Back</a>
            </section>
        </section>
    </main>
</body>
<script src="https://ahmed0saber.github.io/XO-online/external-files/script.js"></script>
<script src="https://kit.fontawesome.com/282bcf757e.js" crossorigin="anonymous"></script>
</html>

app/templates/app/start.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home | XO Online</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=BioRhyme:wght@400&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://ahmed0saber.github.io/XO-online/external-files/style.css">

    <link rel="manifest" href="{% url 'app:manifest' %}">
    <link rel="icon" href="{% static 'logo/tic-tac-toe.svg' %}">
    <meta name="theme-color" content="#1282A2">

</head>
<body>
    <div class="loader">
        <div class="circle"></div>
    </div>
    <header>
        <span class="logo">XO Online</span>
        <nav>
            <div>
                <a class="active" href="{% url 'app:header' %}"><i class="fa fa-home"></i> <span>Home</span></a>
                <a href="{% url 'app:board' %}"><i class="fa fa-trophy"></i> <span>Leaderboard</span></a>
                <a href="{% url 'chat:chat' %}"><i class="fa fa-envelope"></i> <span>Chat</span></a>
                <a href="{% url 'app:notifications' %}"><i class="fa fa-bell"></i> <span>Notifications</span></a>
                <a href="{% url 'accounts:profile' %}"><i class="fa fa-user"></i> <span>Profile</span></a>
            </div>
        </nav>
    </header>
    <main>
        <section class="home">
            <section class="logo-container">
                <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="300" height="300" viewBox="0 0 265 300"><defs><style>.a{clip-path:url(#g);}.b{fill:#1282a2;}.b,.c,.d{font-size:200px;font-family:"BioRhyme";}.c{fill:#f7fff7;}.d{fill:#fff;}.e{fill:#2e3532;}.f{filter:url(#c);}.g{filter:url(#a);}</style><filter id="a" x="13.5" y="-24.5" width="199" height="275" filterUnits="userSpaceOnUse"><feOffset dx="3" dy="3" input="SourceAlpha"/><feGaussianBlur stdDeviation="1.5" result="b"/><feFlood/><feComposite operator="in" in2="b"/><feComposite in="SourceGraphic"/></filter><filter id="c"><feOffset dx="3" dy="3" input="SourceAlpha"/><feGaussianBlur stdDeviation="1.5" result="d"/><feFlood flood-opacity="0.702" result="e"/><feComposite operator="out" in="SourceGraphic" in2="d"/><feComposite operator="in" in="e"/><feComposite operator="in" in2="SourceGraphic"/></filter><clipPath id="g"><rect width="300" height="300"/></clipPath></defs><g id="f" class="a"><rect class="e" width="300" height="300"/><g class="g" transform="matrix(1, 0, 0, 1, 0, 0)"><text class="b" transform="translate(17 187)"><tspan x="0" y="0">X</tspan></text></g><g data-type="innerShadowGroup"><text class="c" transform="translate(113 244)"><tspan x="0" y="0">O</tspan></text><g class="f" transform="matrix(1, 0, 0, 1, 0, 0)"><text class="d" transform="translate(113 244)"><tspan x="0" y="0">O</tspan></text></g></g></g></svg>
            </section>
            <section class="btns">
                <a href="{% url 'app:single' %}">Single Player</a>
                <a href="{% url 'app:two' %}">Two Players</a>
                <a href="{% url 'app:about' %}">About US</a>
            </section>
        </section>
    </main>
</body>
<script src="https://ahmed0saber.github.io/XO-online/external-files/script.js"></script>
<script>
    if ('serviceWorker' in navigator){
        navigator.serviceWorker.register('/sw.js')
    }
</script>
<script src="https://kit.fontawesome.com/282bcf757e.js" crossorigin="anonymous"></script>
</html>

app/templates/app/two.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Two Players | XO Online</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=BioRhyme:wght@400&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://ahmed0saber.github.io/XO-online/external-files/style.css">
</head>
<body>
    <div class="loader">
        <div class="circle"></div>
    </div>
    <header>
        <span class="logo">XO Online</span>
        <nav>
            <div>
                <a class="active" href="{% url 'app:header' %}"><i class="fa fa-home"></i> <span>Home</span></a>
                <a href="{% url 'app:board' %}"><i class="fa fa-trophy"></i> <span>Leaderboard</span></a>
                <a href="{% url 'chat:chat' %}"><i class="fa fa-envelope"></i> <span>Chat</span></a>
                <a href="{% url 'app:notifications' %}"><i class="fa fa-bell"></i> <span>Notifications</span></a>
                <a href="{% url 'accounts:profile' %}"><i class="fa fa-user"></i> <span>Profile</span></a>
            </div>
        </nav>
    </header>
    <main>
        <section class="home">
            <section class="logo-container">
                <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="300" height="300" viewBox="0 0 265 300"><defs><style>.a{clip-path:url(#g);}.b{fill:#1282a2;}.b,.c,.d{font-size:200px;font-family:"BioRhyme";}.c{fill:#f7fff7;}.d{fill:#fff;}.e{fill:#2e3532;}.f{filter:url(#c);}.g{filter:url(#a);}</style><filter id="a" x="13.5" y="-24.5" width="199" height="275" filterUnits="userSpaceOnUse"><feOffset dx="3" dy="3" input="SourceAlpha"/><feGaussianBlur stdDeviation="1.5" result="b"/><feFlood/><feComposite operator="in" in2="b"/><feComposite in="SourceGraphic"/></filter><filter id="c"><feOffset dx="3" dy="3" input="SourceAlpha"/><feGaussianBlur stdDeviation="1.5" result="d"/><feFlood flood-opacity="0.702" result="e"/><feComposite operator="out" in="SourceGraphic" in2="d"/><feComposite operator="in" in="e"/><feComposite operator="in" in2="SourceGraphic"/></filter><clipPath id="g"><rect width="300" height="300"/></clipPath></defs><g id="f" class="a"><rect class="e" width="300" height="300"/><g class="g" transform="matrix(1, 0, 0, 1, 0, 0)"><text class="b" transform="translate(17 187)"><tspan x="0" y="0">X</tspan></text></g><g data-type="innerShadowGroup"><text class="c" transform="translate(113 244)"><tspan x="0" y="0">O</tspan></text><g class="f" transform="matrix(1, 0, 0, 1, 0, 0)"><text class="d" transform="translate(113 244)"><tspan x="0" y="0">O</tspan></text></g></g></g></svg>
            </section>
            <section class="btns">
                <p>Which mode do you prefer to play ?</p>
                <a href="{% url 'app:local' %}">Local</a>
                <a href="{% url 'app:new_game' %}">Online</a>
                <a href="{% url 'app:header' %}"><i class="fa fa-angle-left"></i> Back</a>
            </section>
        </section>
    </main>
</body>
<script src="https://ahmed0saber.github.io/XO-online/external-files/script.js"></script>
<script src="https://kit.fontawesome.com/282bcf757e.js" crossorigin="anonymous"></script>
</html>